server:
  port: 7900
 
eureka:
  client:
    service-url:
      defaultZone : http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true 

      
spring:
  application:
    name: service_provider