server:
  port: 7901
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: movie-ribbon-without-eureka-v1
    
ribbon:
  eureka:
   enabled: false
   
user-v1:
  ribbon:
    listOfServers: localhost:7902